### ISSUE TITLE
Voice Catching Issues

### ISSUE THREAD

**Issue by lakshay774** [TalAter/annyang#102]
Hi,
TalAter Your Script Is Really Good I Have Used It And I Am Trying To Make Something Out Of It But There Are Some Errors In It Like It's Not Catching A Indian Name. Can You Help Me Out With That.
And I Want To Play And Pause Video's On Voice Commands Can You Help Me With That Too ?
If You Want To Check My Sample That What I Am Doing Please Go Through : 
www.zebrogs.com/demo
The Script Is Something Like This 
First Say 
Hello (It Will Say Hello And Ask Your Name)
Adam (Then She Will Ask You What It Can Help You With)
Porn (It Will Say The Admin Don't Allow Me To Use Such Words)
Google (It Will Ask You That Should It Open www.google.com)
Yes (Then She Will Open www.google.com in new tab)
Thanks (It Will Welcome You)

Please Try It And Let Me Know How I Can Use Multiple Commands.

And The Script Is Just Awesome.

Thanks

**Comment by TalAter** [comment]
Demo looks good.

As for Indian names, since you're running it with the language set to 'en-US' it will have trouble recognizing Indian names... my name isn't recognized either.

As for controlling a video, embed a video player that can be controlled via javascript, and call those commands from annyang.
