### ISSUE TITLE
Very slow detection

### ISSUE THREAD

**Issue by poshetz** [TalAter/annyang#120]
Hi, what may cause the detection to be so slow?

It takes like 4/5 seconds before to detect the command.

Is it annyang related?

Because the example on your website (https://www.talater.com/annyang/), looks very fast detected.....

**Comment by TalAter** [comment]
Are you using HTTPS or HTTP in your site? It works much, much faster in HTTPS because it is able to turn off continuous mode.

You can also turn continuous mode off yourself on HTTP by passing it in the options `annyang.start({continuous: false });`
It should work faster, but will also cause Chrome to repeatedly ask for permission to use the mic after every recognition (which isn't done in HTTPS)

**Comment by poshetz** [comment]
@TalAter thank you understood now :)
