### ISSUE TITLE
Ability to use annyang.js without a localhost or a online webserver

### ISSUE THREAD

**Issue by addonmaster** [TalAter/annyang#131]
Hi,

Would be it possible to use annyang.js without a localhost or a online webserver

I mean that annyang.js will just need the Internet to get the command the user said

I do not want to buy a host on the Internet for my project if it is possible not to

Thanks

**Comment by addonmaster** [comment]
Hi,

Do you know if the javascript library for Python, can run annyang.js in the javascript library for Python ?

Thanks

**Comment by JeffCarpenter** [comment]
If you need free hosting, you can use Dropbox for static-only and Heroku for other sites.

And for the time being (as of March 25, 2016), annyang.js only works on Webkit based browsers since it depends on the W3 Web Speech API, so there is little doubt that the Python library you are referencing will not support it.
