### ISSUE TITLE
Userscript - microphone keeps popping up. Also a way to recognize speech faster?

### ISSUE THREAD

**Issue by Ogarunite** [TalAter/annyang#167]
Hi, i've tried adding the examplecode to a tampermonkey userscript on chrome. However, every couple seconds chrome's popup window appears asking for microphone access. How can this be prevented to ask only once? I noticed that if i keep saying commands to the script, it won't question. But as soon as i'm quiet for about 5 seconds, the popup comes.

`// ==UserScript==
// @name          22
// @namespace     http://www.reddit.com/u/undergroundmonorail
// @description   Say a message out loud to say it into chat.
// @include       http://tagpro-*.koalabeast.com:*
// @include       http://tangent.jukejuice.com:*
// @include       http://maptest.newcompte.fr:*
// @include       http://justletme.be*
// @require       http://cdnjs.cloudflare.com/ajax/libs/annyang/2.1.0/annyang.min.js
// @license       MIT
// @author        monorail
// @version       0.2
// ==/UserScript==

if (annyang) {
  // Let's define our first command. First the text we expect, and then the function it should call
  var commands = {
    'show tps report': function() {
        console.log('called');
    },
          'split': function() {
        console.log('split');
    },
                'dash': function() {
        console.log('dash');
    },
                  'fun': function() {
        console.log('fun');
    }
  };

  // Add our commands to annyang
  annyang.addCommands(commands);

  // Start listening. You can call this here, or attach this call to an event, button, etc.
  annyang.start();
}`

Another thing i'm wondering is, how can i speed up the process to recognize a word? There are only 2 words i would like recognized, they are "dash" and "split". I noticed it takes about 1-2 seconds before console.log() outputs it. Is it possible to slow the speed down to perhaps 0.5 seconds or less?

**Comment by jamesarm97** [comment]
Same here just today. From what I read if you have chrome accessing an http site it always asks for permission but if https it will remember or ask once. I was adding in this to the magic mirror project and basically ran into this and stopped for now.

**Comment by Ogarunite** [comment]
The website it's supposed to run on doesn't contain https. There must be a way to bypass this message popping up every few seconds. Maybe inject the script directly, or something?

**Comment by rmilesson** [comment]
I think you're running into a security measure by Chrome. Here you have a bunch of different solutions http://stackoverflow.com/questions/17069979/chrome-always-allow-webcam-over-http.

**Comment by jamesarm97** [comment]
Here is another that may be related but I only see values for do not allow and prompt. Maybe 1 is always allow?

DefaultMediaStreamSetting (deprecated)
Default mediastream settingData type:Integer [Windows:REG_DWORD]Windows registry location:Software\Policies\Chromium\DefaultMediaStreamSettingMac/Linux preference name:DefaultMediaStreamSettingSupported on:
Chromium (Linux, Mac, Windows) since version 22
Chromium OS (Chromium OS) since version 22
Supported features:Dynamic Policy Refresh: Yes, Per Profile: YesDescription:

Allows you to set whether websites are allowed to get access to media capture devices. Access to media capture devices can be allowed by default, or the user can be asked every time a website wants to get access to media capture devices.

If this policy is left not set, 'PromptOnAccess' will be used and the user will be able to change it.
2 = Do not allow any site to access the camera and microphone
3 = Ask every time a site wants to access the camera and/or microphone
Example value:0x00000002 (Windows), 2 (Linux), 2 (Mac)

**Comment by jamesarm97** [comment]
I even found this but it didn’t seem to help:

https://creativcoders.wordpress.com/2014/08/18/chrome-always-allow-access-to-webcam-and-microphone-over-http-webrtc/

**Comment by jamesarm97** [comment]
So annoying. I have tried everything. Clicking the X instead of answering allow or deny makes the box go away. Then you can click the X on the camera icon on url and say always allow which adds an exception. This works only until you refresh the page even though the exception is in my privacy settings. I don't get it.

**Comment by asantos00** [comment]
Are you serving the file with a webserver or directly from file? Chrome blocks some APIs when you serve directly from file (sorry if it is a stupid question)
