### ISSUE TITLE
Verry slow

### ISSUE THREAD

**Issue by Totoajax** [TalAter/annyang#182]
When I run on localhost it is very slow to understand what I'm saying, sometimes ut takes up to a minute. It takes more time if I've "*tag" on the end of the command. On your website it's working really really fast, how do you do that?

**Comment by TalAter** [comment]
The Speech Recognition runs significantly slower on HTTP than on HTTPS. This is because on HTTP it has to use continuous mode or else you would get repeated security notices ([code](https://github.com/TalAter/annyang/blob/master/annyang.js#L132)).

Let me explain the issue.

1. When you first turn on SpeechRecognition the browser asks the user for permission. If the connection is over HTTPS, the browser will remember the user choice and not ask again. If it is on HTTP it will ask again every time you turn it on.

2. The browser returns results in continuous mode much slower than non-continuous mode.

3. In non-continuous mode the SpeechRecognition is stopped after each result is returned.

So when annyang detects HTTPS is available it turns off continuous mode, lets results come back faster and immediately restarts the SpeechRecognition as soon as it is stopped. This wouldn't be practical in HTTP as the browser would continuously ask the user for permission after every sentence. This means you end up with slower results on HTTP than over HTTPS.

You can force continuous mode to be off even in HTTP by passing that setting when starting SpeechRecognition.

````javascript
annyang.start({ continuous: false });
````

**Comment by Totoajax** [comment]
Aha, thank you!

**Comment by prateek1985** [comment]
@TalAter , Hi I am using annyang in HTTP and for fast response I have set continuous mode to be off in annyang but chrome has asked my permission for mic only once and rest all the time its working fine without asking any permission. But as mentioned in this thread that in HTTP the browser would continuously ask the user for permission after every sentence

So I want to know is it useful and safe to make continuous mode off in HTTP ?
