### ISSUE TITLE
Annyang in Chromium

### ISSUE THREAD

**Issue by kelvien** [TalAter/annyang#188]
So, I have been trying to develop an app that uses Annyang library.
However, when I test this in Chromium (in Raspberry Pi), it is not working.

I'm suspecting that the API requests limit in Chromium has passed (Without an API key). Therefore I went ahead to enable my own account's Web Speech API. Then I placed my API key and client ID, secret in my Raspberry pi environment variable, rebooted it, and try to test Annyang in my Chromium.
In my Google Dev Console, it is indicated that I made almost 100 API calls within a minute. It also says that I had a client error 4**, and yes the homepage commands were not working (Hello, Show me cute kittens) (Since I have not used my Web Speech API before, I should not have passed the 50 requests limit) 

This might be more like a Chromium issue, but I'm throwing it here in case if anyone has an idea of what is happening here?
I'm thinking that with my unused Web Speech API call limit, Annyang should work. 

I'm using Chromium 48 (https://www.raspberrypi.org/forums/viewtopic.php?t=121195) in Raspberry Pi 3 (Raspbian Jessie)

**Comment by ctrlaltdylan** [comment]
@kelvien having the same issue, have you made any progress? I'm `console.log`'ing my commands but nothing it showing yet. Haven't isolated if it's a mic issue or annyang on the page.

**Comment by shekit** [comment]
Having the same issue here though I have electron(uses chromium) running on MacOSX El Capitan. I swear annyang was working fine in my project but a couple hours later I tried again without making any change to my code and it refused to work. I pulled a couple of electron projects that use annyang and tried them and still did not get any response.

However I know it isn't a mic issue since annyang seems to be working fine on @TalAter 's site from my computer.

I have the debug message activated and the only debug message I get is that my command has been successfully added. Nothing after that.

I was playing around with annyang a couple of months ago and never faced this problem.

**Comment by kelvien** [comment]
Okay, so my conclusion with using WebSpeech API in Chromium is that there is a limit in using it. I have tested Annyang in RPi's Chromium for 4 consecutive days and it always works early in the morning (I'm assuming that the API limit has been resetted sometime in the morning) and it won't work anymore by the evening. (I don't change any settings that will affect my audio input/output)
https://www.chromium.org/developers/how-tos/api-keys 
This link also explains the API limit usage in Chromium browser that strengthens my belief that the API limit has always been reached by the time I test it again in the evening.
My solution now is to use Chrome, I haven't experienced WebSpeech being down while using it in Chrome browsers

**Comment by shekit** [comment]
@kelvien how have you got chrome running on the RPi? I was under the impression that you can only run Chromium on it..

**Comment by kelvien** [comment]
@shekit Sorry for not being clear in my answer, my solution now is to use Chrome in my personal computers (Not RPi). You are right, RPi can only run Chromium

**Comment by christinadan** [comment]
@shekit Have you been able to figure out the issue with Annyang + Electron? Am also running into the same issue...

**Comment by shekit** [comment]
@kelvien's conclusion seems to be the most plausible. My app again started working in the morning and stopped in the evening. Has to be something with the API call limits.

**Comment by evancohen** [comment]
I've created a workaround documented here: http://docs.smart-mirror.io/docs/chromium_speech_keys.html

It's not the best solution (because you only get 50 requests/day), but at least it's a way to get your own quota rather than relying on the quota for chromium (which is universal to all users?)

**Comment by artforlife** [comment]
Since you gentlemen say that it works in Chromium, should I assume that I can use it in an Ionic app?

**Comment by evancohen** [comment]
@artforlife I've done this before, it works :) you are going to want to use crosswalk and the Cordova media plugin. Because it's an Android user agent you get unlimited speech requests, so you don't need your own custom keys (as far as I know).

**Comment by artforlife** [comment]
@evancohen Since you have done it, what is the most efficient way of doing this? I currently have a MEAN stack app that I will be porting to Ionic as well. The voice feature is not implemented on it yet, but I have been playing around with it. On the mobile app, the voice feature becomes much more crucial.

**Comment by macdonst** [comment]
@artforlife oh, if you are going to use Cordova you can try my plugin on Android/iOS. https://github.com/macdonst/SpeechRecognitionPlugin

**Comment by evancohen** [comment]
In an existing ionic app run:
``` bash
ionic browser add crosswalk
cordova plugin add cordova-plugin-media
```
Now `webkitSpeechRecognition` should work just as it does in Chrome (without needing to add keys). Two caveats:

- This will only work on Android devices that have a speech recognizer (which is bundled with the Google Now app), so using a device like the Kindel Fire won't work unless you sideload that app.
- The app will ding with the native sound, you have no control over this. See #194.

@TalAter I believe this issue is resolved, feel free to close it out.

**Comment by TalAter** [comment]
Thank you @evancohen for all the awesome work.

As you are the person most familiar with this issues, I have got to ask... would you consider writing a few Q&As about these issues for the [FAQ](https://github.com/TalAter/annyang/blob/master/docs/FAQ.md)? Looks like it could help a lot of people.

**Comment by evancohen** [comment]
@TalAter It would be my pleasure. I'll take a stab at it this week.

**Comment by Hakim2014** [comment]
Hi All, 

I am new to electron apps and trying to build an app with voice functionality.  I did some google search and found that I need the GOOGLE_API_KEY, CLIENT ID and SECRET key for annyang to work with electron app. I created one and set as environment variable  on my windows and then try to run the app. I added the call back function to annyang and it always console out network error. Please let me know if I am doing something wrong over here . I want to run this app on my raspberry also, but couldn't find any success.

**Comment by mojave-doug-f** [comment]
I don't know much about electron. Is there a reason you would use is instead of Google chrome?

**Comment by Hakim2014** [comment]
I am developing a desktop application which runs on device as an app. And electron uses nodejs modules and chromium to achieve this. So I am using electron .
