### ISSUE TITLE
Annyang.pause() not working

### ISSUE THREAD

**Issue by shekit** [TalAter/annyang#193]
## Expected Behavior

I am calling annyang.pause() when a certain command is detected and then calling annyang.resume() after a certain interval. annyang should stop detecting commands after I say the keyword.

## Current Behavior

I have annyang.debug() on and it continues to print out detected speech even after I have called annyang.pause(). Moreover when I call annyang.resume() , it says 

`Failed to execute 'start' on 'SpeechRecognition': recognition has already started.`

If I call annyang.abort() instead and then annyang.resume() then I do not get this error and it does stop detecting commands.

annyang.isListening() however returns false

## Steps to Reproduce (for bugs)

1. include annyang.debug
2. add a command to your command list
3. call annyang.pause() when the command is detected (in it's function)
4. call annyang.resume() after a few seconds

## Your Environment

* Version used: 2.4
* Browser Name and version: Chromium Electron
* Operating System and version (desktop or mobile): Desktop Mac OSX El Capitan
* Link to your project:

**Comment by TalAter** [comment]
Interesting. I was just able to replicate this issue.
Thank you 👍 I am looking into this.

**Comment by atchyut-re** [comment]
Hello, Shekit that issue is because of the usage of annyang.start() command you might have used for the auto start of speech recognition on page start. annyang.resume() is being execute and starting the voice recognition at same time annyang.start() stating that recognition has already started.

**Comment by TalAter** [comment]
The following code replicates the issue:
````javascript
<html>
<body>
  <script src="//cdnjs.cloudflare.com/ajax/libs/annyang/2.4.0/annyang.min.js"></script>
  <script>
  "use strict";
  var logStatus = function() {
    console.log('annyang.isListening()', annyang.isListening());
  };
  if (annyang) {
    var commands = {
      'hello': function() {
        logStatus();
        annyang.pause();
        logStatus();
        setTimeout(logStatus, 500);
      }
    }
    annyang.addCommands(commands);
    annyang.start();
  }
  </script>
</body>
</html>
````

I believe I have found the problem in annyang, and hope to release a fix later today.

**Comment by TalAter** [comment]
This issue was caused because annyang was set to autorestart and it was in continuous mode (which caused it to stop and restart after every sentence recognized).

When annyang restarted itself, it also resumed itself (turned off the paused state).

This has been fixed and released as [v2.5.0](https://github.com/TalAter/annyang/tree/v2.5.0).

Thanks for the help identifying the problem.

**Comment by atchyut-re** [comment]
Thanks for the update TalAter, 
But this `Failed to execute 'start' on 'SpeechRecognition': recognition has already started.` error is being shown. When I use `annyang.resume();`

**Comment by TalAter** [comment]
@atchyut-re  I am aware of this, and it is by design.

But you are right, it is not ideal... so I just took another look at it to see if it would be possible to change this behaviour.

Since the browser's Speech Recognition object does not expose anything that would allow us to check if it is on or not, we would need to test against annyang's `isListening` variable.

We could test `if (isListening)` in [`annyang.resume()`](https://github.com/TalAter/annyang/blob/master/annyang.js#L348) or [`annyang.start()`](https://github.com/TalAter/annyang/blob/master/annyang.js#L305), and not start Speech Recognition it if it is already listening.

Unfortunately, this means relying on isListening which is an internal variable that annyang keeps in order to see if the Speech Recognition is on or not... it is the most reliable form for checking if it is on or not that I am aware of... but when the user tries to resume or start, I prefer to try and start the Speech Recognition again regardless of this annyang variable just to be on the safe side.

I think showing an error in one small case (only for sites that use `pause()` and `resume()`), and even that is only when debug is on, is a small tradeoff for having it more reliable and predictable for all other users.

**Comment by atchyut-re** [comment]
What you said was right and can be done for time being.

But the annyang.pause() is not pausing the recognition for long time. When it is called, it is doing good. for some time, after that it is resuming itself.
This is causing the error `Failed to execute 'start' on 'SpeechRecognition': recognition has already started.` when annyang.resume() is triggered. 

This is what I had observed till now.

**Comment by TalAter** [comment]
This should be fixed by now. Have you observed this in v2.5.0?

If so, please provide code that reproduces the issue so it will be easier to understand and fix this.

Thank you.

**Comment by gwitwer** [comment]
Had this issue in 2.5 after switching from 1.4. After "empty cache and hard reload" in Chrome, problem was resolved.
