### ISSUE TITLE
How the annyang parse commands in languages from right to left.

### ISSUE THREAD

**Issue by sayeko** [TalAter/annyang#260]
Hey, I encounter in a situation that I need to you annyang for custom languages that been writing from right to left. And I can't determine how the annyang with english to pass function parameter.

I found one solution that worked for me but I don't quite sure it the right or proper solution.

## Expected Behavior
I think is the proper way because it should look for right to left.
var commands : {
['*to' + 'שלח']: function(to) {console.log(to)} 
}

## Current Behavior
var commands : {
['שלח' + '*to']: function(to) {console.log(to)} 
}

## Possible Solution
Determine if the language is from right to left and run over the commands properties.

**Comment by TalAter** [comment]
The current behavior is the correct one in my opinion.

`שלח *to` is how you would write it in a right to left language... it only looks backwards because the code editor is rendering text left-to-right (even if you type it right-to-left)

![ltr](https://cloud.githubusercontent.com/assets/926653/24825244/67ed5fac-1be0-11e7-812e-4f853baec487.gif)
