### ISSUE TITLE
Enabling annyang to work for Chrome mobile

### ISSUE THREAD

**Issue by drubio1989** [TalAter/annyang#271]
I was wondering if the annyang library is compatible with Chrome for iphone? I am creating a 3D visualizer with AFrame and while the desktop version works. It seems that annyang does not work at all on mobile. Does annyang support this feature? Perhaps there is a setting on chrome that needs to be enabled? I love this library and can see the potential in WebVr applications.

**Comment by TalAter** [comment]
Speech recognition works in Chrome for Android, but not in Chrome on iOS devices.

That's because Chrome on iOS isn't really Chrome.

Apple does not allow third-party browsing engines on their devices. All third-party browsers on their devices are just wrappers around iOS WebKit engine.

In other words. When you are using Chrome on your iPhone, you are basically using Safari with a Chrome facade around it... and Safari doesn't support Speech Recognition (among other things).

**Comment by nsbrijesh** [comment]
We have implemented Annyang deeply in our web application without realizing that it won't work on iOS devices. And now after investing so much time on it, it will cost us a lot to scrap and start from scratch. Can you please suggest some ideas so as to not start from the beginning. Any work around or pollyfill to go with Annyang?

**Comment by TalAter** [comment]
You can try one of the paid services that does speech recognition from [AWS](https://aws.amazon.com/transcribe/), [GCP](https://cloud.google.com/speech-to-text/), or [Azure](https://azure.microsoft.com/en-in/services/cognitive-services/speech-to-text/). But you would still need to write some sort of polyfill that will replace the speechrecognition so that annyang could use it.

Just an idea, I haven't tried doing that myself.
I did write a replacement for the browser's speechrecognition for testing purposes - https://github.com/TalAter/Corti/ - this might give you some ideas on where to start.

**Comment by nsbrijesh** [comment]
Thanks for the quick reply. I will look into these.

**Comment by Klaushbgv1992** [comment]
@nsbrijesh wondering if to ever managed to get around it? I managed to get English working on iOS devices but not on other languages.
