### ISSUE TITLE
How can I end the speech to text recognition and switch to recognize command.

### ISSUE THREAD

**Issue by kranil1989927** [TalAter/annyang#273]
var addPageDesc = function(){
					$('#pageDescription').focus();
					
					var r = document.getElementById('pageDescription');					
					var speechRecognizer = annyang.getSpeechRecognizer();
					speechRecognizer.continuous = true;
					speechRecognizer.interimResults = true;

					var finalTranscripts = '';

					speechRecognizer.onresult = function(event){
						var interimTranscripts = '';
						for(var i = event.resultIndex; i < event.results.length; i++){
							var transcript = event.results[i][0].transcript;
							transcript.replace("\n", "<br>");							
							if(event.results[i].isFinal){
								finalTranscripts += transcript;
							}else{
								interimTranscripts += transcript;
							}
						}					
						r.innerHTML = finalTranscripts + interimTranscripts;
					};
					speechRecognizer.onerror = function (event) {
					};
				};
I can switch from command recognition to speech to text recognition. I want to know how can I end the
speech to text recognition and  switch back to command recognition.

Thanks

**Comment by TalAter** [comment]
Your code effectively overwrites annyang's `onresult` event handler so that it cannot listen to any further results.

This is way outside of what annyang was designed to do, as your code effectively "breaks" annyang... but here are two ideas of what you might try.

1. Instead of `speechRecognizer.onresults = func`, try `speechRecognizer.addEventListener('result', func)`. This will not delete annyang's speech recognition. Be sure to pause annyang when you want to use your "text recognition" mode.
2. I have never tried this... but it may be possible to create more than one speech recognition object in one window. Let annyang do it's thing, and when you want to switch to "text recognition", pause annyang and use your own speech recognition (replacing `var speechRecognizer = annyang.getSpeechRecognizer();` with `var speechRecognizer = new webkitSpeechRecognition();`

**Comment by kranil1989927** [comment]
Thanks for your reply with possible solution.
I will pause annyang when I want to use your "text recognition" mode.  How can I decide that I have done with 'text recognition' want to switch back to 'command recognition'.

Thanks,
Anil Kumar

**Comment by TalAter** [comment]
When you want to turn annyang back on just run `annyang.resume()`.

I encourage you to read the [API docs](https://github.com/TalAter/annyang/blob/master/docs/README.md) to see all of the available options.
