### ISSUE TITLE
Section Refresh 

### ISSUE THREAD

**Issue by ardakazanci** [TalAter/annyang#285]
Hello , When I say the same command again, I want your content to be renewed.

I play a game and when I say the same command again I want to update it for that section.
I'm sorry for my bad english

**Comment by TalAter** [comment]
annyang just runs functions based on certain commands. If you want those functions to do different things every time you call them, you can keep track of how many times they were called.

Anyway, this sounds like something that needs to be implemented in your own game's code, and not within annyang. I can't really help because I do not know your code.

Good luck 👍
