### ISSUE TITLE
Support for onspeechstart/speechstart event

### ISSUE THREAD

**Issue by mohitadwani** [TalAter/annyang#291]
## Expected Behavior

You should implement an onspeechstart/speechstart event for the user to know when speech activity is detected.

## Current Behavior

You have provided an event called 'soundstart' which is fired as soon as ANY sound is detected. There should be a specific event when speech is detected. 

## Context

I am implementing an online proctoring system which should detect and record whenever the user speaks. For that I need the speechstart event. The functionality of speechend event is provided by the 'result' event.

**Comment by TalAter** [comment]
Unfortunately, this isn't possible because of a bug in Chrome which I reported and explained here: https://bugs.chromium.org/p/chromium/issues/detail?id=572697&thanks=572697&ts=1451323087

I encourage you to add a comment to the end of that thread and ask them if they plan on addressing this.

You can also read more about the discussion of how this bug was found on #103
