### ISSUE TITLE
Add multi language support

### ISSUE THREAD

**Issue by TalAter** [TalAter/annyang#3]
annyang already supports receiving commands in any language.
Just call:

```
// choose language
annyang.setLanguage('it-IT');

// define commands in that language
annyang.init({
  'mi chiamo *name': sayHello
});
```

Need to add support for defining rules in multiple languages, and then a user should be able to just change the language without redefining rules:

```
// choose language
annyang.setLanguage('it-IT');

// define commands in that language
annyang.init(
  'it-IT': {
    'mi chiamo *name': sayHello
  },
  'en' : {
    'my name is *name': sayHello
  }
});

annyang.setLanguage('en');
// now annyag recognizes English
annyang.setLanguage('it-IT');
// now annyag recognizes Italian
```

See how this can be added without breaking existing code (can define either multiple languages, or one)

**Comment by panos138** [comment]
hello,i just realize that this perfect project not support Greek.I think its not so good for Greeks and for Greece.,is there any possibility to add GREEK?

**Comment by TalAter** [comment]
@panos138 - Unfortunately the language support is up to the browser... Google Chrome in this case. They choose which languages they support; I can't control this.

**Comment by panos138** [comment]
hi my friend,congratulations for the project,its awesome!!!
Google supports greek check here

https://www.google.com/intl/en/chrome/demos/speech.html

**Comment by TalAter** [comment]
@panos138 - Then so does annyang.
````javascript
annyang.setLanguage('el-GR');
````

**Comment by panos138** [comment]
thank you!!!

**Comment by Anewryzm** [comment]
This project is absolutely amazing!
Thanks for work on it and make we can get it for free.

**Comment by shuffledpixels** [comment]
I don't get it how I make it work with multiple languages... Here's my code:

```
if (annyang) {
    annyang.debug();
    annyang.setLanguage('en-US');

    var greeting = function() {
        $chatStatus.html('Hello! How are you?');
    };
    var cumprimento = function() {
        $chatStatus.html('Olá! Como estás?');
    };

    annyang.addCommands({
        'en-US': {
            'hello': greeting
        },
        'pt-PT' : {
            'olá': cumprimento
        }
    });

    annyang.setLanguage('en-US');
    // now annyag recognizes English
    annyang.setLanguage('pt-PT');
    // now annyag recognizes Portuguese
    annyang.start();
}
```

**Comment by TalAter** [comment]
@heliochun There is actually no way to make it work with multiple languages at the same time... it is able to detect speech, not recognize which language the user is speaking... you have to tell it what language to recognize.

**Comment by popbijoux** [comment]
**COMMENT:**
One answer and one question, pigging back on what Helio just asked. I am working with several languages (so far have only tested English) and I assume the easiest thing for Helio would be something you mentioned earlier. Meaning define the function in the main language and add any other corresponding words into the same function.  [https://github.com/TalAter/annyang/issues/251](url)
![screen shot 2017-04-11 at 6 48 26 pm](https://cloud.githubusercontent.com/assets/21673735/24934427/8316b8d0-1ee9-11e7-9c3a-c6bf2112a9f1.png)
Tal's full answer here: [https://github.com/TalAter/annyang/issues/119](url)
**QUESTION:**
Thinking about this issue, is there a way to set the language via the browser, i.e. if the user clicks on a button she can choose a different language? [extrapolating from the tutorial you have]. I am guessing the answer is "NO" but wanted to double-check:)

For example:
//user says the word "Portuguese 
var commands = {
  'Portuguese': changeToPortuguese
};
//this command sets the language to Portuguese
var changeToPortuguese = function() {
 annyang.setLanguage('pt-PT');
}
 
I wanted to know, broadly, if there any way to set these preferences via the browser_ so that the user could change the language command somehow? 

_The broader, "umbrella" question is, is there a way to have users change commands directly? That would be huge but I am not sure that can be done:)_

**Comment by heliochun** [comment]
Thank you for your response @TalAter .

That's actually a great idea @popbijoux !
Structuring languages by many different files (`annyang-en.js`, `annyang-fr.js` etc) and then let the user choose the language on their side using a `<select>` and based on the chosen language, call the file containing all the functions already prepared for that language. Although this might require a page refresh to make a new request and maybe set a cookie.

**Comment by JK1306** [comment]
sir how to make to recognize to an unsupported language

**Comment by BiblioVee** [comment]
Hello, I'm new here! Is there any possibility of adding Welsh to annyang? We are trying to get our library catalogue 'Voice Search Assistant' to recognise Welsh. At the moment, the search results when speaking Welsh are appalling. Grateful of any advice. Thank you.

**Comment by pixelismo** [comment]
I'm making a translator for a dead language. And I'm including words from an array, but it shows me English words or the selected language first.
In my case, it would be very useful if it only searched the array or at least gave priority to those words.
Excellent work!
