### ISSUE TITLE
Function with default parameter

### ISSUE THREAD

**Issue by energiatel** [TalAter/annyang#307]
How can use function with default parameter?

```
commands['scroll'] = scrollTo; //Works
annyang.addCommands(commands);

commands['scroll'] = scrollTo('500'); //Not Works
annyang.addCommands(commands);
```

```

var scrollTo = function(pixel = 100)
{
	jQuery('html, body').animate({scrollTop: jQuery(window).scrollTop() + pixel});
}
```

Couldn't use API reference syntax to add command because i got javascript error (my commands and function are loaded from database):

`var commands = {'hello :name': helloFunction, 'howdy': helloFunction};`

**Comment by TalAter** [comment]
`commands['scroll'] = scrollTo('500');` Would not work because you are not defining a function but calling it and then placing whatever it returns into the commands object.

I think your best bet would be to check within `scrollTo` if a parameter was received, and if not set the value you want as a default in it.
