### ISSUE TITLE
Using annyang for speech dictation into a form field 

### ISSUE THREAD

**Issue by ashduggan** [TalAter/annyang#324]
**GOAL: Allowing a user to dictate multiple lines of text into a form field when a command is spoken without it disappearing** 
## Expected Behavior
I'd like to be able to have a person be able to dictate text into the text field they are currently on. Basically, you say something while a form field is highlighted and on a command, you can say wherever you want and it gets put into only that field. 

## Current Behavior
Currently, I have it so that I can record one set of phrases at a time into a certain field which I have specified by ID. 

`annyang.addCallback('result',function(whatWasHeard) {
  document.getElementById("frmObj").value = whatWasHeard[0];  
}); `

This idea was taken from a previous example from [https://github.com/TalAter/annyang/issues/293](url)

I understand that this is using an array to store the spoken words and only shows the first value of the array. Is there a way to continuously record text on a command with annyang?

## Your Environment
Google Chrome

**Comment by popbijoux** [comment]
Hi Ashley, I am not sure what you mean exactly by your question. I had posted the original question #293, followed the example from Tal's answer on #293 and it worked perfectly ... exactly as you phrased it:

"I'd like to be able to have a person be able to dictate text into the text field they are currently on. Basically, you say something while a form field is highlighted and on a command, you can say wherever you want and it gets put into only that field."

But it only does show the most recent text. For example if I say "I am going to get lunch" and then wait a little bit, the next phrase will automatically delete the previous text. If I say "I'm hungry" it will delete the previous "I am going to get lunch". Now only "I'm hungry"  is visible. It does show on the actual div previously specified. The "first value on the array" that Tal meant, in my case meant only the closest match is displayed, whereas before, several options would be displayed, meaning, 

"For example if I say the word "toast",
I get first, toast, 1st, post"

Do you mean that you want the previous text not to be automatically deleted and remain visible, like for example the app https://speechnotes.co/ ?, where it keeps everything?

**Comment by popbijoux** [comment]
Ashley this is the code from a page I used a while back just to test Annyang transcription and it worked perfectly. You can obvs add an input form instead of a random div, as long as the ID is the same it should work.

<body>

    `<div id="voiceToText" type="text" name="lastname">

</div>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/annyang/2.6.0/annyang.min.js"></script>

<script>
if (annyang) {
  // Let's define a command.
  var commands = {
    'hello': function() { alert('Hello world!'); }
  };

  // Add our commands to annyang
  annyang.addCommands(commands);

  // Start listening.
  annyang.start();
}



annyang.addCallback('result',function(whatWasHeard) {
  document.getElementById("voiceToText").innerHTML = whatWasHeard[0];
});
</script>

</body>
</html>

**Comment by ashduggan** [comment]
Yes, sorry if my post was confusing. That example of [speechnote](https://speechnote.co) is exactly what I am looking to accomplish. The trouble I'm having now is the text is deleted after a new set of words is spoken. I also only want it to insert the text into a form when a certain command is spoken. So for example, if I said "record text" then it would start inserting whatever I said next into the form field. Does that make sense?
