### ISSUE TITLE
TypeScript documentation

### ISSUE THREAD

**Issue by erperejildo** [TalAter/annyang#351]
I installed this using `npm install --save @types/annyang`

Can you provide more info about service name, location and implementation?

**Comment by jordi72** [comment]
I'm also trying to use Annyang in angular 7
I've used `npm install annyang --save` and `npm install --save @types/annyang`
I've this simple code 
![annyang_code](https://user-images.githubusercontent.com/8350580/56032360-4d613c00-5d22-11e9-8eaf-9572bd478216.png)

i know commands is showing error, im following the tutorial, and simply doesn't works, but the main error is in the next image.

![annyang_error](https://user-images.githubusercontent.com/8350580/56032394-65d15680-5d22-11e9-8d91-4996ad97d924.png)

i can't use any method of Annyang because it's undefined.
Can you please provide a guide for typescript or just help me? :)

**Comment by cristianrablau** [comment]
@erperejildo the next step is to add the following in your angular.json or angular-cli.json depending on your Angular version:

`"scripts": [
              "node_modules/annyang/dist/annyang.min.js"
            ],`

After that you can use it anywhere:

`import { Component, OnInit } from '@angular/core';
import { Annyang } from 'annyang';

declare var annyang: Annyang;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {

  title = 'Angular';

  ngOnInit(): void {
    this.init();
  }

  init() {
    var commands = { "hello": this.writeHello }
    annyang.addCommands(commands);
    annyang.start();
  }

  writeHello() {
    console.log("Hello");
  }
}`

@jordi72 I think this should work for you :)
Use `declare var` to declare annyang from the js file and specify it is of type Annyang for compile errors and IntelliSense.

**Comment by erperejildo** [comment]
Thanks for the response. I'm no longer working on this already but I'll have a look if I find any problem when I go back to this.

Cheers!
