### ISSUE TITLE
Speech interactions

### ISSUE THREAD

**Issue by hajsf** [TalAter/annyang#354]
Is there a way to do `Speech interactions` something like:

```
    'hi (my friend) :name': function(name) { 
        speak('Hello '+name+', How can I help you?');

            recognition.onresult = function (event) {
                for (var i = event.resultIndex; i < event.results.length; ++i) {
                    if (event.results[i].isFinal) {
                        var result = event.results[i][0].transcript;
                        speak('You said: '+result);
                    } 
                    }
            };
    },


where:
function speak(text) {
	var msg = new SpeechSynthesisUtterance();
	msg.text = text;
        msg.lang = 'en-US';
        msg.voice = speechSynthesis.getVoices()[7];
	msg.volume = 1;
	msg.rate = 1;
	msg.pitch = 1;
	window.speechSynthesis.speak(msg);
}
```

**Comment by sethwilsonUS** [comment]
Currently the best way I can think of to do this is to create a new set of `newCommands` within the `hi (my friend) :name` function, back up the original commands to a variable if needed, and then add those `newCommands` using the `annyang.init(newCommands, true)` command. The `true` means annyang will remove the original set of commands. Then, after your interactive function has finished, you can re-initialize annyang with the original commands.

Maybe not super-elegant, but should achieve the result you're looking for. I'm thinking about doing something similar in a project I'm working on.

**Comment by TalAter** [comment]
@sethwilsonUS Let me suggest a small improvement on your idea:

Instead of calling `init()` you can call `removeCommands()` without passing it any params (which will remove all commands) followed by `addCommands(yourCommandsArray)`.

`init()` should only be called once as it does things like abort existing Speech Recognition sessions and adds all the event listeners.

This way you can replace all the commands without restarting the speech recognition (which might prompt an extra permission request from the user or extra beeping on mobile)
