### ISSUE TITLE
Simplest Example Not Working

### ISSUE THREAD

**Issue by rjonesxmoz** [TalAter/annyang#371]
I am trying a simple capture for my daughter's birthday party. I want to capture attempts at saying spells from Harry Potter :-)

At any rate, the most basic tests is failing.

http://clarenjones.com/harrypotter/test.html

It should alert "Hello World" when I say Hello.

The only modification I made to the code was a test to make sure that annyang was actually loaded, and it was,

=======================

Operating system Windows NT 10.0
IP address 104.59.236.102
Javascript enabled Yes
Cookies enabled Yes
Flash version Not installed
Java version Not installed
Websockets supported Yes
Browser size 2545 x 1310
Screen size 2560 x 1440
Color depth 24 bit
Your full user agent string is:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by TalAter** [comment]
My guess would be that this is because you are not on HTTPS. Google deprecated support for non-secure locations in Chrome's Speech Recognition.

Try running the same code but with HTTPS, or on `localhost`.

Closing for now. If this is still an issue, feel free to reopen the issue with more details.

Good luck and... happy birthday!
