### ISSUE TITLE
Webpage does not mention language support

### ISSUE THREAD

**Issue by AndersBillLinden** [TalAter/annyang#397]
Although multi language support is provided, the webpage does not mention anything about it.
Lets presume that is a key aspect for most users.

**Comment by asp2809** [comment]
Hey @AndersBillLinden, I think the webpage mentions the **multilingual support of the library **.
Here is a screenshot:
![image](https://user-images.githubusercontent.com/29016076/66147529-a902e700-e62c-11e9-88da-e24d8ec09ddf.png)
Do you want to show anything more specific than that?

**Comment by TalAter** [comment]
This was an intentional choice as annyang itself does not contain the individual languages support because it does not contain the speech recognition engine. The speech recognition - and supporting different languages - is up to the browsers and differs from browser to browser.

The FAQ does go into more detail than that - https://github.com/TalAter/annyang/blob/master/docs/FAQ.md#what-languages-are-supported
